name: CI
on: [push, pull_request]

jobs:
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build on linux with clang
        run: |
          make release
        env:
          CC: clang
  build-macos-gcc:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build on macos with clang
        run: |
          make release
        env:
          CC: clang