name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build on linux with gcc
        run: |
          make
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build on linux with clang
        run: |
          make
        env:
          CC: clang
build-windows-msvc:
    runs-on: windows-2019
    steps:
      - name: force LF
        shell: cmd
        run: |
          git config --global core.autocrlf input
      - uses: actions/checkout@v1
        # this runs vcvarsall for us, so we get the MSVC toolchain in PATH.
      - uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: build everything
        shell: cmd
        # this replaces default PowerShell, which can't fail the build
        run: |
          .\build_msvc.bat