name: CI
on: [push, pull_request]

jobs:
  build-linux-gcc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build on linux with gcc
        run: |
          make release
        env:
          CC: gcc
  build-linux-clang:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build on linux with clang
        run: |
          make release
        env:
          CC: clang
  build-macos-gcc:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Build on macos with clang
        run: |
          make release
        env:
          CC: clang
  build-macos-gcc:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get install mingw-w64
          dpkg --add-architecture i386 
          wget -nc -O /usr/share/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          wget -nc -P /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources 
          apt update
          apt install --install-recommends winehq-stable
       - name: build
         run: |
           make release
        - name: test
          run: |
            make test
        env:
          CC: x86_64-w64-mingw32-gcc